// <auto-generated />
namespace TodoAspNetMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSomeRecordsTodoItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSomeRecordsTodoItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202011211536034_AddSomeRecordsTodoItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
